import box from '../images/Box.png'
import huntingBoard23Players from '../images/HuntingBoard23players.png'
import huntingBoard45Players from '../images/HuntingBoard45players.png'
import caveBlue from '../images/CaveBlue.png'
import caveGreen from '../images/CaveGreen.png'
import caveRed from '../images/CaveRed.png'
import caveWhite from '../images/CaveWhite.png'
import caveYellow from '../images/CaveYellow.png'
import cardBackBlue from '../images/HunterBlueBack.jpg'
import cardBackWhite from '../images/HunterWhiteBack.jpg'
import cardBackGreen from '../images/HunterGreenBack.jpg'
import cardBackRed from '../images/HunterRedBack.jpg'
import cardBackYellow from '../images/HunterYellowBack.jpg'
import hunterBlue1_1 from '../images/HunterBlue1-1.png'
import hunterBlue1_2 from '../images/HunterBlue1-2.png'
import hunterBlue2_1 from '../images/HunterBlue2-1.png'
import hunterBlue2_2 from '../images/HunterBlue2-2.png'
import hunterBlue3_1 from '../images/HunterBlue3-1.png'
import hunterBlue3_2 from '../images/HunterBlue3-2.png'
import hunterBlue4_1 from '../images/HunterBlue4-1.png'
import hunterBlue4_2 from '../images/HunterBlue4-2.png'
import hunterBlue5_1 from '../images/HunterBlue5-1.png'
import hunterBlue5_2 from '../images/HunterBlue5-2.png'
import hunterBlue6_1 from '../images/HunterBlue6-1.png'
import hunterBlue6_2 from '../images/HunterBlue6-2.png'
import hunterWhite1_1 from '../images/HunterWhite1-1.png'
import hunterWhite1_2 from '../images/HunterWhite1-2.png'
import hunterWhite2_1 from '../images/HunterWhite2-1.png'
import hunterWhite2_2 from '../images/HunterWhite2-2.png'
import hunterWhite3_1 from '../images/HunterWhite3-1.png'
import hunterWhite3_2 from '../images/HunterWhite3-2.png'
import hunterWhite4_1 from '../images/HunterWhite4-1.png'
import hunterWhite4_2 from '../images/HunterWhite4-2.png'
import hunterWhite5_1 from '../images/HunterWhite5-1.png'
import hunterWhite5_2 from '../images/HunterWhite5-2.png'
import hunterWhite6_1 from '../images/HunterWhite6-1.png'
import hunterWhite6_2 from '../images/HunterWhite6-2.png'
import hunterGreen1_1 from '../images/HunterGreen1-1.png'
import hunterGreen1_2 from '../images/HunterGreen1-2.png'
import hunterGreen2_1 from '../images/HunterGreen2-1.png'
import hunterGreen2_2 from '../images/HunterGreen2-2.png'
import hunterGreen3_1 from '../images/HunterGreen3-1.png'
import hunterGreen3_2 from '../images/HunterGreen3-2.png'
import hunterGreen4_1 from '../images/HunterGreen4-1.png'
import hunterGreen4_2 from '../images/HunterGreen4-2.png'
import hunterGreen5_1 from '../images/HunterGreen5-1.png'
import hunterGreen5_2 from '../images/HunterGreen5-2.png'
import hunterGreen6_1 from '../images/HunterGreen6-1.png'
import hunterGreen6_2 from '../images/HunterGreen6-2.png'
import hunterRed1_1 from '../images/HunterRed1-1.png'
import hunterRed1_2 from '../images/HunterRed1-2.png'
import hunterRed2_1 from '../images/HunterRed2-1.png'
import hunterRed2_2 from '../images/HunterRed2-2.png'
import hunterRed3_1 from '../images/HunterRed3-1.png'
import hunterRed3_2 from '../images/HunterRed3-2.png'
import hunterRed4_1 from '../images/HunterRed4-1.png'
import hunterRed4_2 from '../images/HunterRed4-2.png'
import hunterRed5_1 from '../images/HunterRed5-1.png'
import hunterRed5_2 from '../images/HunterRed5-2.png'
import hunterRed6_1 from '../images/HunterRed6-1.png'
import hunterRed6_2 from '../images/HunterRed6-2.png'
import hunterYellow1_1 from '../images/HunterYellow1-1.png'
import hunterYellow1_2 from '../images/HunterYellow1-2.png'
import hunterYellow2_1 from '../images/HunterYellow2-1.png'
import hunterYellow2_2 from '../images/HunterYellow2-2.png'
import hunterYellow3_1 from '../images/HunterYellow3-1.png'
import hunterYellow3_2 from '../images/HunterYellow3-2.png'
import hunterYellow4_1 from '../images/HunterYellow4-1.png'
import hunterYellow4_2 from '../images/HunterYellow4-2.png'
import hunterYellow5_1 from '../images/HunterYellow5-1.png'
import hunterYellow5_2 from '../images/HunterYellow5-2.png'
import hunterYellow6_1 from '../images/HunterYellow6-1.png'
import hunterYellow6_2 from '../images/HunterYellow6-2.png'
import objective0 from '../images/Objective0.png'
import objective1A from '../images/Objective1A.png'
import objective1B from '../images/Objective1B.png'
import objective2A from '../images/Objective2A.png'
import objective2B from '../images/Objective2B.png'
import objective3A from '../images/Objective3A.png'
import objective3B from '../images/Objective3B.png'
import objective4A from '../images/Objective4A.png'
import objective4B from '../images/Objective4B.png'
import objective5A from '../images/Objective5A.png'
import objective5B from '../images/Objective5B.png'
import objective6A from '../images/Objective6A.png'
import objective6B from '../images/Objective6B.png'
import objective7A from '../images/Objective7A.png'
import objective7B from '../images/Objective7B.png'
import objective8A from '../images/Objective8A.png'
import objective8B from '../images/Objective8B.png'
import objective9A from '../images/Objective9A.png'
import objective9B from '../images/Objective9B.png'
import totemBlue from '../images/TotemBlue.jpg'
import totemWhite from '../images/TotemWhite.jpg'
import totemGreen from '../images/TotemGreen.jpg'
import totemRed from '../images/TotemRed.jpg'
import totemYellow from '../images/TotemYellow.jpg'
import polyominoType0HunterBlue from '../images/PolyominoType0-HunterBlue.png'
import polyominoType0HunterWhite from '../images/PolyominoType0-HunterWhite.png'
import polyominoType0HunterGreen from '../images/PolyominoType0-HunterGreen.png'
import polyominoType0HunterRed from '../images/PolyominoType0-HunterRed.png'
import polyominoType0HunterYellow from '../images/PolyominoType0-HunterYellow.png'
import polyominoType0TotemBlue from '../images/PolyominoType0-TotemBlue.png'
import polyominoType0TotemWhite from '../images/PolyominoType0-TotemWhite.png'
import polyominoType0TotemGreen from '../images/PolyominoType0-TotemGreen.png'
import polyominoType0TotemRed from '../images/PolyominoType0-TotemRed.png'
import polyominoType0TotemYellow from '../images/PolyominoType0-TotemYellow.png'
import polyominoType1_1 from '../images/PolyominoType1-1.png'
import polyominoType1_2 from '../images/PolyominoType1-2.png'
import polyominoType1_3 from '../images/PolyominoType1-3.png'
import polyominoType1_4 from '../images/PolyominoType1-4.png'
import polyominoType1_5 from '../images/PolyominoType1-5.png'
import polyominoType2_1A from '../images/PolyominoType2-1A.png'
import polyominoType2_1B from '../images/PolyominoType2-1B.png'
import polyominoType2_2A from '../images/PolyominoType2-2A.png'
import polyominoType2_2B from '../images/PolyominoType2-2B.png'
import polyominoType2_3A from '../images/PolyominoType2-3A.png'
import polyominoType2_3B from '../images/PolyominoType2-3B.png'
import polyominoType2_4A from '../images/PolyominoType2-4A.png'
import polyominoType2_4B from '../images/PolyominoType2-4B.png'
import polyominoType2_5A from '../images/PolyominoType2-5A.png'
import polyominoType2_5B from '../images/PolyominoType2-5B.png'
import polyominoType3_1A from '../images/PolyominoType3-1A.png'
import polyominoType3_1B from '../images/PolyominoType3-1B.png'
import polyominoType3_2A from '../images/PolyominoType3-2A.png'
import polyominoType3_2B from '../images/PolyominoType3-2B.png'
import polyominoType3_3A from '../images/PolyominoType3-3A.png'
import polyominoType3_3B from '../images/PolyominoType3-3B.png'
import polyominoType3_4A from '../images/PolyominoType3-4A.png'
import polyominoType3_4B from '../images/PolyominoType3-4B.png'
import polyominoType3_5A from '../images/PolyominoType3-5A.png'
import polyominoType3_5B from '../images/PolyominoType3-5B.png'
import polyominoType3_6A from '../images/PolyominoType3-6A.png'
import polyominoType3_6B from '../images/PolyominoType3-6B.png'
import polyominoType3_7A from '../images/PolyominoType3-7A.png'
import polyominoType3_7B from '../images/PolyominoType3-7B.png'
import polyominoType3_8A from '../images/PolyominoType3-8A.png'
import polyominoType3_8B from '../images/PolyominoType3-8B.png'
import polyominoType3_9A from '../images/PolyominoType3-9A.png'
import polyominoType3_9B from '../images/PolyominoType3-9B.png'
import polyominoType3_10A from '../images/PolyominoType3-10A.png'
import polyominoType3_10B from '../images/PolyominoType3-10B.png'
import polyominoType4_1A from '../images/PolyominoType4-1A.png'
import polyominoType4_1B from '../images/PolyominoType4-1B.png'
import polyominoType4_2A from '../images/PolyominoType4-2A.png'
import polyominoType4_2B from '../images/PolyominoType4-2B.png'
import polyominoType4_3A from '../images/PolyominoType4-3A.png'
import polyominoType4_3B from '../images/PolyominoType4-3B.png'
import polyominoType4_4A from '../images/PolyominoType4-4A.png'
import polyominoType4_4B from '../images/PolyominoType4-4B.png'
import polyominoType4_5A from '../images/PolyominoType4-5A.png'
import polyominoType4_5B from '../images/PolyominoType4-5B.png'
import polyominoType4_6A from '../images/PolyominoType4-6A.png'
import polyominoType4_6B from '../images/PolyominoType4-6B.png'
import polyominoType4_7A from '../images/PolyominoType4-7A.png'
import polyominoType4_7B from '../images/PolyominoType4-7B.png'
import polyominoType4_8A from '../images/PolyominoType4-8A.png'
import polyominoType4_8B from '../images/PolyominoType4-8B.png'
import polyominoType4_9A from '../images/PolyominoType4-9A.png'
import polyominoType4_9B from '../images/PolyominoType4-9B.png'
import polyominoType4_10A from '../images/PolyominoType4-10A.png'
import polyominoType4_10B from '../images/PolyominoType4-10B.png'
import polyominoType5_1 from '../images/PolyominoType5-1.png'
import polyominoType5_2 from '../images/PolyominoType5-2.png'
import polyominoType5_3 from '../images/PolyominoType5-3.png'
import polyominoType5_4 from '../images/PolyominoType5-4.png'
import polyominoType5_5 from '../images/PolyominoType5-5.png'
import whiteBGtest from '../images/whiteBGtest.jpg'
import blueBGtest from '../images/blueBGtest.jpg'
import yellowBGtest from '../images/yellowBGtest.jpg'
import redBGtest from '../images/redBGtest.jpg'
import greenBGtest from '../images/greenBGtest.jpg'
import hunterBG from '../images/hunterBG.png'
import caveBGYellow from '../images/bgCaveYellowTest.jpg'
import powerBlue1 from '../images/powerBlue1.png'
import powerBlue2 from '../images/powerBlue2.png'
import powerBlue3 from '../images/powerBlue3.png'
import powerBlue4 from '../images/powerBlue4.png'
import powerBlue5 from '../images/powerBlue5.png'
import powerRed1 from '../images/powerRed1.png'
import powerRed2 from '../images/powerRed2.png'
import powerRed3 from '../images/powerRed3.png'
import powerRed4 from '../images/powerRed4.png'
import powerRed5 from '../images/powerRed5.png'
import powerWhite1 from '../images/powerWhite1.png'
import powerWhite2 from '../images/powerWhite2.png'
import powerWhite3 from '../images/powerWhite3.png'
import powerWhite4 from '../images/powerWhite4.png'
import powerWhite5 from '../images/powerWhite5.png'
import powerGreen1 from '../images/powerGreen1.png'
import powerGreen2 from '../images/powerGreen2.png'
import powerGreen3 from '../images/powerGreen3.png'
import powerGreen4 from '../images/powerGreen4.png'
import powerGreen5 from '../images/powerGreen5.png'
import powerYellow1 from '../images/powerYellow1.png'
import powerYellow2 from '../images/powerYellow2.png'
import powerYellow3 from '../images/powerYellow3.png'
import powerYellow4 from '../images/powerYellow4.png'
import powerYellow5 from '../images/powerYellow5.png'
import arrowCleanIcon from '../images/arrow.jpg'
import arrowBrokenIcon from '../images/brokenArrow.jpg'

const Images = {

    huntingBoard23Players, huntingBoard45Players,
    caveBlue, caveGreen, caveRed, caveWhite, caveYellow,
    cardBackBlue, cardBackWhite, cardBackGreen, cardBackRed, cardBackYellow, 
    hunterBlue1_1, hunterBlue1_2, hunterBlue2_1, hunterBlue2_2, hunterBlue3_1, hunterBlue3_2, hunterBlue4_1, hunterBlue4_2, hunterBlue5_1, hunterBlue5_2, hunterBlue6_1, hunterBlue6_2,
    hunterWhite1_1, hunterWhite1_2, hunterWhite2_1, hunterWhite2_2, hunterWhite3_1, hunterWhite3_2, hunterWhite4_1, hunterWhite4_2, hunterWhite5_1, hunterWhite5_2, hunterWhite6_1, hunterWhite6_2, 
    hunterGreen1_1, hunterGreen1_2, hunterGreen2_1, hunterGreen2_2, hunterGreen3_1, hunterGreen3_2, hunterGreen4_1, hunterGreen4_2, hunterGreen5_1, hunterGreen5_2, hunterGreen6_1, hunterGreen6_2,
    hunterRed1_1, hunterRed1_2, hunterRed2_1, hunterRed2_2, hunterRed3_1, hunterRed3_2, hunterRed4_1, hunterRed4_2, hunterRed5_1, hunterRed5_2, hunterRed6_1, hunterRed6_2, 
    hunterYellow1_1, hunterYellow1_2, hunterYellow2_1, hunterYellow2_2, hunterYellow3_1, hunterYellow3_2, hunterYellow4_1, hunterYellow4_2, hunterYellow5_1, hunterYellow5_2, hunterYellow6_1, hunterYellow6_2, 
    objective0, objective1A, objective1B, objective2A, objective2B, objective3A, objective3B, objective4A, objective4B, objective5A, objective5B, objective6A, objective6B, objective7A, objective7B, objective8A, objective8B, objective9A, objective9B,
    totemBlue, totemGreen, totemRed, totemWhite, totemYellow, 
    polyominoType0HunterBlue, polyominoType0HunterWhite, polyominoType0HunterGreen, polyominoType0HunterRed, polyominoType0HunterYellow, 
    polyominoType0TotemBlue, polyominoType0TotemWhite, polyominoType0TotemGreen, polyominoType0TotemRed, polyominoType0TotemYellow, 
    polyominoType1_1, polyominoType1_2, polyominoType1_3, polyominoType1_4, polyominoType1_5, 
    polyominoType2_1A, polyominoType2_2A, polyominoType2_3A, polyominoType2_4A, polyominoType2_5A, polyominoType2_1B, polyominoType2_2B, polyominoType2_3B, polyominoType2_4B, polyominoType2_5B, 
    polyominoType3_1A, polyominoType3_2A, polyominoType3_3A, polyominoType3_4A, polyominoType3_5A, polyominoType3_6A, polyominoType3_7A, polyominoType3_8A, polyominoType3_9A, polyominoType3_10A, polyominoType3_1B, polyominoType3_2B, polyominoType3_3B, polyominoType3_4B, polyominoType3_5B, polyominoType3_6B, polyominoType3_7B, polyominoType3_8B, polyominoType3_9B, polyominoType3_10B, 
    polyominoType4_1A, polyominoType4_2A, polyominoType4_3A, polyominoType4_4A, polyominoType4_5A, polyominoType4_6A, polyominoType4_7A, polyominoType4_8A, polyominoType4_9A, polyominoType4_10A, polyominoType4_1B, polyominoType4_2B, polyominoType4_3B, polyominoType4_4B, polyominoType4_5B, polyominoType4_6B, polyominoType4_7B, polyominoType4_8B, polyominoType4_9B, polyominoType4_10B, 
    polyominoType5_1, polyominoType5_2, polyominoType5_3, polyominoType5_4, polyominoType5_5, 

    whiteBGtest, blueBGtest, yellowBGtest, redBGtest, greenBGtest, hunterBG, caveBGYellow,

    powerBlue1, powerBlue2, powerBlue3, powerBlue4, powerBlue5,
    powerRed1, powerRed2, powerRed3, powerRed4, powerRed5,
    powerWhite1, powerWhite2, powerWhite3, powerWhite4, powerWhite5,
    powerGreen1, powerGreen2, powerGreen3, powerGreen4, powerGreen5,
    powerYellow1, powerYellow2, powerYellow3, powerYellow4, powerYellow5,
    arrowCleanIcon, arrowBrokenIcon

}

export const bluePowerBanners = [powerBlue1, powerBlue2, powerBlue3, powerBlue4, powerBlue5]
export const redPowerBanners = [powerRed1, powerRed2, powerRed3, powerRed4, powerRed5]
export const whitePowerBanners = [powerWhite1, powerWhite2, powerWhite3, powerWhite4, powerWhite5]
export const greenPowerBanners = [powerGreen1, powerGreen2, powerGreen3, powerGreen4, powerGreen5]
export const yellowPowerBanners = [powerYellow1, powerYellow2, powerYellow3, powerYellow4, powerYellow5]

export const BlueHunters = [hunterBlue1_1, hunterBlue1_2, hunterBlue2_1, hunterBlue2_2, hunterBlue3_1, hunterBlue3_2, hunterBlue4_1, hunterBlue4_2, hunterBlue5_1, hunterBlue5_2, hunterBlue6_1, hunterBlue6_2]
export const GreenHunters = [hunterGreen1_1, hunterGreen1_2, hunterGreen2_1, hunterGreen2_2, hunterGreen3_1, hunterGreen3_2, hunterGreen4_1, hunterGreen4_2, hunterGreen5_1, hunterGreen5_2, hunterGreen6_1, hunterGreen6_2]
export const RedHunters = [hunterRed1_1, hunterRed1_2, hunterRed2_1, hunterRed2_2, hunterRed3_1, hunterRed3_2, hunterRed4_1, hunterRed4_2, hunterRed5_1, hunterRed5_2, hunterRed6_1, hunterRed6_2]
export const WhiteHunters = [hunterWhite1_1, hunterWhite1_2, hunterWhite2_1, hunterWhite2_2, hunterWhite3_1, hunterWhite3_2, hunterWhite4_1, hunterWhite4_2, hunterWhite5_1, hunterWhite5_2, hunterWhite6_1, hunterWhite6_2]
export const YellowHunters = [hunterYellow1_1, hunterYellow1_2, hunterYellow2_1, hunterYellow2_2, hunterYellow3_1, hunterYellow3_2, hunterYellow4_1, hunterYellow4_2, hunterYellow5_1, hunterYellow5_2, hunterYellow6_1, hunterYellow6_2]

export default Images